apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: demo
  labels:
    env: demo
    managed-by: kpt-fn-render
    app: demo
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
