apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    managed-by: kpt-fn-render
    #app: demo

    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      env: demo
      managed-by: kpt-fn-render
  template:
    metadata:
      labels:
        app: demo
        env: demo
        managed-by: kpt-fn-render
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
